# Q学習で FrozenLake問題(4x4)を解く

In [43]:
import gym
import numpy as np

In [44]:
env = gym.make('FrozenLake-v0')

In [45]:
# Q値を格納する配列を初期化（フィールドの大きさ x 行動数）
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [51]:
lr = 0.8 # 学習率
y = 0.95 # 割引率
num_episodes = 2000 # 学習回数
episode_size = 100 # 一回の学習の移動量

In [54]:
for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    d = False
    move_cnt = 0
    while move_cnt < 99:
        move_cnt += 1
        # Q値が一番高い方向のインデックスを持ってくる ↓学習回数や乱数などのノイズを付与
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n) * (1.0/(i+1)) )
        s1, r, d, _ = env.step(a) # s1:行き先マス, r:動作前のQ[s, a], d: 死んだか
        Q[s, a] = Q[s, a] + lr * (r + y*np.max(Q[s1, :] - Q[s, a]))
        rALL += r # r:動作前のQ[s, a]
        s = s1 # マスの移動
        if d == True:
            break
    rList.append(rAll)
            

In [55]:
print ("回数毎の結果：", str(sum(rList) / num_episodes))

回数毎の結果： 0.0


In [56]:
print("最終的なQテーブルの値")
print(Q)

最終的なQテーブルの値
[[1.82324780e-01 2.32136676e-01 9.34147893e-01 2.25699505e-02]
 [1.36066594e-03 1.30823455e-03 6.71202028e-03 8.76749339e-01]
 [4.56154428e-02 1.00411127e-02 2.53055540e-02 8.45809752e-01]
 [7.06535295e-03 1.01797394e-04 5.46965678e-03 8.42360566e-01]
 [9.26337726e-01 1.18505263e-01 4.98801547e-03 5.64280042e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.88163532e-05 3.49495599e-06 4.11647302e-02 4.85872906e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.30824492e-02 4.31949483e-02 1.80388048e-03 9.28733675e-01]
 [0.00000000e+00 9.86082221e-01 6.39319110e-03 2.65182675e-03]
 [3.71156973e-01 0.00000000e+00 7.61421161e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.01457086e-03 9.64477004e-01 6.90143563e-03]
 [0.00000000e+00 9.85632630e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e